import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { FiCpu, FiLayers, FiInbox } from 'react-icons/fi';
import ProductCard from '../../components/product/ProductCard';
import { getMyOrders } from '../../api/orderApi';
import { getProducts } from '../../api/productApi';
import { getRecommendations } from '../../api/recommendationApi';

export default function RecommendedProductsPage() {
  const [collabRecs, setCollabRecs] = useState([]);
  const [contentRecs, setContentRecs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPersonalizedRecs = async () => {
      setLoading(true);
      try {
        const ordersResponse = await getMyOrders();
        const orders = ordersResponse.data || [];
        
        let anchorProductId = '';
        
        if (orders.length > 0 && orders[0].items && orders[0].items.length > 0) {
          anchorProductId = orders[0].items[0].productId;
        } else {
          // If no purchases, use the first catalog product as anchor
          const catalogResponse = await getProducts({ limit: 1 });
          const catalog = catalogResponse.data.products || [];
          if (catalog.length > 0) {
            anchorProductId = catalog[0]._id;
          }
        }

        if (anchorProductId) {
          const recsResponse = await getRecommendations(anchorProductId);
          const dbRecs = recsResponse.data || [];
          const mappedRecs = dbRecs.map(p => ({
            ...p,
            id: p._id,
            categoryId: p.category.toLowerCase().replace(/\s+/g, '-'),
            rating: p.rating || 5.0,
            reviews: p.reviews || 1,
            author: p.author || { name: 'NeuroUX Team', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NeuroUX' }
          }));

          setCollabRecs(mappedRecs.slice(0, 3));
          setContentRecs(mappedRecs.slice(3, 6));
        }
      } catch (err) {
        console.error("Failed to load personalized recommendations:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchPersonalizedRecs();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#080712]">
        <div className="w-12 h-12 border-4 border-violet-950 border-t-violet-500 rounded-full animate-spin shadow-glow-sm"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#080712] pt-28 pb-24 text-white relative">
      {/* Background accents */}
      <div className="absolute inset-0 dot-grid opacity-15 pointer-events-none" />
      <div className="absolute top-1/4 right-1/4 w-[500px] h-[500px] bg-purple-900/5 blur-[120px] pointer-events-none" />

      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="mb-10">
          <h1 className="text-3xl font-extrabold tracking-tight">
            AI <span className="text-violet-400">Recommendations</span>
          </h1>
          <p className="text-sm text-[#8b7fb5] mt-1 font-light">
            Personalized recommendations generated by the NeuroUX hybrid machine learning pipeline.
          </p>
        </div>

        {/* Section 1: Collaborative Filtering */}
        <div className="mb-12">
          <div className="flex items-center gap-2 border-b border-white/5 pb-3 mb-6">
            <FiCpu className="text-violet-400" size={18} />
            <div>
              <h2 className="text-lg font-bold text-white">Collaborative Behavioral Matches</h2>
              <span className="text-[10px] text-zinc-500 font-bold uppercase tracking-wider block">Suggested based on user interactions</span>
            </div>
          </div>

          {collabRecs.length === 0 ? (
            <div className="text-center py-10 text-[#8b7fb5] text-sm">
              Explore the marketplace to generate personalized recommendations!
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {collabRecs.map((product) => (
                <ProductCard key={product.id} product={product} />
              ))}
            </div>
          )}
        </div>

        {/* Section 2: Content-Based Similarity */}
        <div>
          <div className="flex items-center gap-2 border-b border-white/5 pb-3 mb-6">
            <FiLayers className="text-cyan-400" size={18} />
            <div>
              <h2 className="text-lg font-bold text-white">Category Affinity Suggestions</h2>
              <span className="text-[10px] text-zinc-500 font-bold uppercase tracking-wider block">Suggested based on product similarity</span>
            </div>
          </div>

          {contentRecs.length === 0 ? (
            <div className="text-center py-10 text-[#8b7fb5] text-sm">
              More suggestions will appear here once you checkout.
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {contentRecs.map((product) => (
                <ProductCard key={product.id} product={product} />
              ))}
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
